version: "3.3"

# Do not forget that the only available 
# selenium hub image is accessible with the following url:
# registry.gitlab.com/qio/standard/selenium/hub:4.10.0

# Do not forget that the only available 
# selenium node-chrome image is accessible with the following url:
# registry.gitlab.com/qio/standard/selenium/node-chrome:4.10.0

# Do not forget that the only available 
# selenium node-firefox image is accessible with the following url:
# registry.gitlab.com/qio/standard/selenium/node-firefox:4.10.0

# Do not forget that the only available 
# nginx image is accessible with the following url:
# registry.gitlab.com/qio/standard/nginx:1.20.2-alpine


services:
  selenium-hub:
    image: registry.gitlab.com/qio/standard/selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: registry.gitlab.com/qio/standard/selenium/node-chrome:4.10.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: registry.gitlab.com/qio/standard/selenium/node-firefox:4.10.0
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  nginx:
    image: registry.gitlab.com/qio/standard/nginx:1.20.2-alpine
    container_name: nginx-server
    ports:
      - "8081:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
